import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";
import { Terminal } from "@/components/Terminal";
import { Background } from "@/components/Background";
import { Footer } from "@/components/Footer";
import { Cursor } from "@/components/Cursor";
import { SystemProvider } from "@/context/SystemContext";
import { Toaster } from "@/components/ui/sonner";
// import { KeyboardNavigation } from "@/components/KeyboardNavigation";
import { HomeButton } from "@/components/HomeButton";
import { getProfile } from "@/lib/db";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const profile = await getProfile();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <SystemProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Cursor />
            <Background />
            {/* <KeyboardNavigation /> */}
            <HomeButton image={profile.image} />
            <div className="flex-1 flex flex-col relative z-10">
               {/* Main Content Frame Container */}
               <main className="flex-1 flex flex-col max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
                  {children}
               </main>
               <Footer />
               <Terminal />
               <Toaster />
            </div>
          </ThemeProvider>
        </SystemProvider>
      </body>
    </html>
  );
}
